dedef
hotel_cost(nights):
return 140 * nights


def plane_ride_cost(*city)


    if "charlotte" == city
        retuen
        183
    elif "Tampa" == city
    return 220
elif "Pittsburgh" == city
return 222
elif "los angeles" == city
return 475
elif days >= 3:
else:
return 40 * days


def trip_cost(city, days, spending_money)
    return rental_car_cost(days + hotel_cost(days + plane_ride_cost(city))) + spending_money


print("cost of car rental: ", rental_car_cost(5))
print("cost of car rental:", plane_ride_cost("los angeles"))
print("cost of hotel room", hotel_cost(7))
print("total cost of the trip", trip
cost("los angeles", 7, 500))
print(trip_cost("TamPa", 6, 500))
f
hotel_cost(nights):
    return 140*nights
def plane_ride_cost(*city)
    if "charlotte" == city
        retuen 183
    elif "Tampa" == city
    return 220
elif "Pittsburgh" == city
return 222
elif "los angeles" == city
return 475
elif days>=3:
else:
return 40*days
def trip_cost(city, days, spending_money)
    return rental_car_cost(days + hotel_cost(days + plane_ride_cost(city))) + spending_money
print("cost of car rental: ",  rental_car_cost(5))
print("cost of car rental:",   plane_ride_cost("los angeles"))
print("cost of hotel room", hotel_cost(7))
print("total cost of the trip",trip cost("los angeles",7,500))
print(trip_cost("TamPa",6,500))