import random
import time
def getRandomDate(startDate , endDate):
    print("rnadom date between", start date "and" , endDate)
    randomGenretor = random.random()
    dateformat = "%m/%d/%Y"
    startTime = time.mktime(time.strptime(startDate, dateFormat))
    endTime = time.mktime(time.strptime(endDte, dateFormat))
    return rnadomDate
    print("random date =", getRandomDate("1/1/2016", "12/12/2018")